// Generated by scripts/runtime-bytecode.mjs. Do not edit by hand.
export const PONG_RUNTIME_BYTECODE_METADATA = {
  engine: "quickjs",
  engineVersion: "2025-09-13",
  format: "quickjs-binary-json-bytecode",
  formatVersion: "5",
  evalType: "global",
  mediaType: "application/vnd.sayso.quickjs-bytecode",
} as const;
